### PR TITLE
Optionally allow duplicated mutations when using load_vcf or load_maf. Fixes #211 

### LINKED ISSUE #211: Optionally allow duplicated mutations when using load_vcf or load_maf
Let's give user an option to allow duplicated variants when loading variants from a VCF or MAF by adding `distinct` parameter of `VariantCollection` to `load_vcf` and `load_maf`.

### PR DESCRIPTION
**Pull request by tuomastik**
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/varcode/212)

### CODE REVIEW

**Comment by iskandr** [comment]
Looks like this failed on Travis because of unrelated (need to install Ensembl 87 on travis), I'll fix that shortly and re-run your tests.

**Comment by iskandr** [comment]
Hey @tuomastik I merged your other PR and I think that created merge conflicts with this one. I also moved the confusing sort order of `VariantCollection` to a separate issue. Thanks for these PRs! Sorry I've been slow in getting to them.

**Comment by tuomastik** [comment]
Thanks @iskandr and no worries about the time taken! I just resolved the conflicts with the base branch.

**Comment by iskandr** [comment]
Hey @tuomastik, I'll update the Varcode version on PyPI later today, thanks for the PR!

**Pull request merged**
